# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b3a42a61dfe3772e08db89ebec22a20748b5712ebf4e42b3cfa6f3d7f7eb553dc0ceaa25b93229fa054a8645a5819fa4aada4702ec52718dbe34a7bafa14f8

test:
  secret_key_base: 5eb49cf631b317d5e9c872b5b4ed0dac40daaa0098e20e5055d19e26ac00f5ac8393b117d29c729c4a5bd701d556799727e280ca052db54bacd3001c410a4a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
